from pydantic import BaseModel, Field
from typing import Optional

class RagRequest(BaseModel):
    query: str = Field(..., description="The query to be processed by the RAG system.")

class RagUsedContext(BaseModel):
    image_url: str = Field(..., description="URL of the item's image")
    price: Optional[float] = Field(None, description="Price of the item")
    description: str = Field(..., description="Description of the item")

class RagResponse(BaseModel):
    request_id : str = Field(..., description="A unique identifier for the RAG request, useful for tracking and debugging.")
    answer: str = Field(..., description="The answer generated by the RAG system in response to the query.")
    used_context: list[RagUsedContext] = Field(..., description="A list of context items that were used to generate the answer. Each item includes its ID and relevance score.")