
import numpy
from openai import OpenAI
from qdrant_client import QdrantClient
from langsmith import traceable, get_current_run_tree
from pydantic import BaseModel, Field
import instructor
from qdrant_client.models import VectorParams, Distance, PointStruct, PayloadSchemaType, SparseVectorParams, Document, Prefetch, FusionQuery, Filter, FieldCondition, MatchValue
from qdrant_client import models
from api.agents.local_models import client, EMBED_MODEL

from api.agents.utils.prompt_management import prompt_template_config

class RagUsedContext(BaseModel):
    id: str = Field(..., description="ID of the item used to answer the question")
    description: str = Field(..., description="Description of the item ised to answer the question")

class RAGGenerationResponse(BaseModel):
    answer: str = Field(..., description="Answer generated by the RAG pipeline")
    references: list[RagUsedContext] = Field(..., description="List of the items used to generate the answer")


client = OpenAI(
    base_url="http://ollama:11434/v1",
    api_key="ollama",
)

@traceable(
    name="embedding_query",
    run_type="embedding",
    metadata={
        "ls_provider": "ollama",
        "ls_model_name": "nomic-embed-text",
    },
)
def get_embedding(text, model="nomic-embed-text"):
    response = client.embeddings.create(
        input=text,
        model=model,
    )

    run = get_current_run_tree()
    if run and getattr(response, "usage", None):
        run.set(
            usage_metadata={
                "input_tokens": response.usage.prompt_tokens,
                # для embeddings output_tokens обычно нет
                "total_tokens": response.usage.total_tokens,
            }
        )

    return response.data[0].embedding


@traceable(
    name="retrieve_data",
    run_type="retriever",
)

def retrieve_data(query, qdrant_client, top_k=5):
    query_embedding = get_embedding(query)
    search_result = qdrant_client.query_points(
        collection_name="Amazon_items_collection1_hybrid_search",
        prefetch = [
            Prefetch(
             query=query_embedding,
             using="nomic-embed-text",
             limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm-25",
                limit=20
                )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=top_k
    )

    retrieved_context_ids = []
    retrieved_contexts = []
    similarity_scores = []
    retrieved_context_ratings = []

    for point in search_result.points:
        retrieved_context_ids.append(point.payload["parent_asin"])
        retrieved_contexts.append(point.payload["description"])
        retrieved_context_ratings.append(point.payload["average_rating"])
        similarity_scores.append(point.score)

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_contexts": retrieved_contexts,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }


def process_context(context):
    processed_context = ""
    for id_, chunk, rating in zip(
        context["retrieved_context_ids"],
        context["retrieved_contexts"],
        context["retrieved_context_ratings"]
    ):
        processed_context += f"-ID {id_}: rating: {rating}, description: {chunk}\n"
    return processed_context


def build_prompt(query, context):
    template = prompt_template_config("api/agents/prompts/retrieval_generation.yaml", "retrieval_generation")
    prompt = template.render(query=query, context=context)
    return prompt


@traceable(
    name="generate_answer",
    run_type="llm",
    metadata={
        "ls_provider": "ollama",
        "ls_model_name": "qwen2.5:7b",
        # необязательно, но полезно для фильтрации/аналитики
        "ls_temperature": 0,
    },
)
def generate_answer(prompt):
    
    client = instructor.from_provider(
        "ollama/qwen2.5:7b",
            base_url="http://ollama:11434/v1",
            api_key="ollama",
        mode = instructor.Mode.JSON,
    )
    response = client.create(
         messages=[
            {
                "role": "system",
                "content": "You are a helpful shopping assistant that can answer questions about products based on the available products."
            },
            {"role": "user", "content": prompt}
        ],
        response_model = RAGGenerationResponse,
        timeout = 10.0,
        max_retries= 2,
    )


    # response = client.chat.completions.create(
    #     model="gemma3:4b",
    #     messages=[
    #         {
    #             "role": "system",
    #             "content": "You are a helpful shopping assistant that can answer questions about products based on the available products."
    #         },
    #         {"role": "user", "content": prompt}
    #     ],
    #     response_model = RAGGenerationResponse
    # )

    # run = get_current_run_tree()
    # if run and getattr(response, "usage", None):
    #     run.set(
    #         usage_metadata={
    #             "input_tokens": response.usage.prompt_tokens,
    #             "output_tokens": response.usage.completion_tokens,
    #             "total_tokens": response.usage.total_tokens,
    #         }
    #     )

    return response


@traceable(
    name="rag_pipeline",
    run_type="chain",
)
def rag_pipeline(query, qdrant_client, top_k=5):
    retrieved_data = retrieve_data(query, qdrant_client, top_k)
    processed_context = process_context(retrieved_data)
    prompt = build_prompt(query, processed_context)
    answer = generate_answer(prompt)

    final_result = {
        "answer": answer.answer,
        "references": answer.references,
        "question": query,
        "retrieved_context": retrieved_data["retrieved_contexts"],
        "retrieved_context_ids": retrieved_data["retrieved_context_ids"],
        "similarity_scores": retrieved_data["similarity_scores"],
    }

    return final_result



def rag_pipeline_wrapper(question, top_k=5):
    qdrant_client = QdrantClient(
        url="http://qdrant:6333",
    )

    result = rag_pipeline(question, qdrant_client, top_k)
    used_context = []
    dummy_vector = numpy.zeros(768).tolist() 
    for item in result.get("references", []):
        payload = qdrant_client.query_points(
            collection_name="Amazon_items_collection1_hybrid_search",
            query=dummy_vector,
            with_payload=True,
            using ="nomic-embed-text",
            limit=1,
            query_filter= Filter(
                must =  [
                    FieldCondition(
                        key="parent_asin",
                        match= MatchValue(value=item.id)
                        )
                    ])
        ).points[0].payload
        image_url = payload.get("image")
        price = payload.get("price")
        if image_url:
            used_context.append({
                "image_url": image_url,
                "price": price,
                "description": item.description
            })

    return {
        "answer": result["answer"],
        "used_context": used_context,
    }


# from openai import OpenAI
# from qdrant_client import QdrantClient


# from langsmith import traceable, get_current_run_tree

# from openai import OpenAI

# client = OpenAI(
#     base_url="http://ollama:11434/v1",
#     api_key="ollama",  
# )

# @traceable(
#     name="embedding_query",
#     run_type="embedding",
#     # metadata={"ls_provider": "openai", "ls_model_name ": "nomic-embed-text"}
# )
# def get_embedding(text, model="nomic-embed-text"):
#     response = client.embeddings.create(
#         input=text,
#         model=model,
#     )

#     curent_tree = get_current_run_tree()
#     if curent_tree:
#         curent_tree.metadata["usage_meatadata"] = {
#             "model_name": model,
#             "input_tokens": response.usage.prompt_tokens,
#             "total_tokens": response.usage.total_tokens,
#         }

#     return response.data[0].embedding

# @traceable(
#     name="retrieve_data",
#     run_type="retriever",
# )
# def retrieve_data(query , qdrant_client, top_k=5):
#     query_embedding = get_embedding(query)
#     search_result = qdrant_client.query_points(
#         collection_name="Amazon_items_collection1",
#         query_vector=query_embedding,
#         limit=top_k
#     )

#     retrieved_context_ids = []
#     retrieved_contexts = []
#     similarity_scores = []
#     retrieved_context_ratings = []

#     for point in search_result.points:
#         retrieved_context_ids.append(point.payload["parent_asin"])
#         retrieved_contexts.append(point.payload["description"])
#         retrieved_context_ratings.append(point.payload["average_rating"])
#         similarity_scores.append(point.score)

#     return {
#         "retrieved_context_ids": retrieved_context_ids,
#         "retrieved_contexts": retrieved_contexts,
#         "similarity_scores": similarity_scores,
#         "retrieved_context_ratings": retrieved_context_ratings
#     }


# # @traceable(
# #     name="process_context",
# #     run_type="processing",
# # )
# def process_context(context):
#     processed_context = ""
#     for id, chunk, rating in zip(context["retrieved_context_ids"], context["retrieved_contexts"], context["retrieved_context_ratings"]):
#         processed_context += f"-ID {id}: rating: {rating}, description: {chunk}\n"
#     return processed_context



# # @traceable(
# #     name="build_prompt",
# #     run_type="prompting",
# # )
# def build_prompt(query, context):
#     prompt = f"""You are shopping assistant that can answer questions about products. 
#     You will be given a question and some retrieved information about products.
    
#     Instructions:
#     - You need to use only the retrieved information to answer the question.
#     - Never use word context and refer to it as the available products.

#     Context:
#     {context}

#     Question:
#     {query}  """

#     return prompt



# @traceable(name="generate_answer",
#            run_type="llm",)
# #               metadata={"ls_provider": "openai", "ls_model_name ": "text-embedding-3-small"})
# def generate_answer(prompt):
#     response = client.chat.completions.create(
#         model="gemma3:4b",
#         messages=[
#             {"role": "system", "content": "You are a helpful shopping assistant that can answer questions about products based on the available products."},
#             {"role": "user", "content": prompt}
#         ],
#     )
    
    
#     # curent_tree = get_current_run_tree()
#     # if curent_tree:
#     #     curent_tree.metadata["usage_meatadata"] = {
#     #         "input_tokens": response.usage.prompt_tokens,
#     #         "output_tokens": response.usage.completion_tokens,
#     #         "total_tokens": response.usage.total_tokens,
#     #     }


#     return response.choices[0].message.content


# # @traceable( 
# #     name="rag_pipeline",
# #     run_type="llm_pipeline"
# # )
# def rag_pipeline(query, top_k=5):
#     qdrant_client = QdrantClient(
#         url="http://qdrant:6333",)
#     retrieved_data = retrieve_data(query, qdrant_client, top_k)
#     processed_context = process_context(retrieved_data)
#     prompt = build_prompt(query, processed_context)
#     answer = generate_answer(prompt)

#     # final_result = {
#     #     "query": query,
#     #     "answer": answer,
#     #     "retrieved_context": retrieved_data["retrieved_contexts"],
#     #     "retrieved_context_ids": retrieved_data["retrieved_context_ids"],
#     #     "similarity_scores": retrieved_data["similarity_scores"],
#     # }

#     return answer